; Generated by ezcompiler — Inno Setup script
; Editable: rerun `ezcompiler generate iss --force` to regenerate from config.

#define MyAppName "MyApp"
#define MyAppPublisher "ACME Corp"

[Setup]
AppId={{A1B2C3D4-1111-2222-3333-444455556666}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
VersionInfoVersion={#VersionInfo}
AppPublisher={#MyAppPublisher}
AppPublisherURL=https://acme.example
AppSupportURL=https://acme.example/support
AppUpdatesURL=https://acme.example/updates
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
DefaultDirName={autopf}\{#MyAppName}
PrivilegesRequired=admin
DefaultGroupName=ACME Tools
OutputDir={#OutputDir}
OutputBaseFilename=MyApp-{#MyAppVersion}-setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
CloseApplications=force
RestartApplications=yes
SignTool=mytool

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#BundleDir}\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MainExe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MainExe}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MainExe}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Flags: preservestringtype

[UninstallDelete]
Type: filesandordirs; Name: "{app}\cache"
