; Generated by ezcompiler — Inno Setup script
; Editable: rerun `ezcompiler generate iss --force` to regenerate from config.

#define MyAppName "MyApp"
#define MyAppPublisher "ACME Corp"

[Setup]
AppId={{CAE3F4E7-B3D9-5E4B-AF0B-FA86334D34E1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
VersionInfoVersion={#VersionInfo}
AppPublisher={#MyAppPublisher}
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
DefaultDirName={localappdata}\Programs\{#MyAppName}
PrivilegesRequired=lowest
DefaultGroupName=MyApp
OutputDir={#OutputDir}
OutputBaseFilename=MyApp-{#MyAppVersion}-setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
CloseApplications=force
RestartApplications=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#BundleDir}\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MainExe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MainExe}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MainExe}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}"; Flags: preservestringtype; Check: NeedsAddPath(ExpandConstant('{app}'))

[Code]
// Anti-duplicate guard for the [Registry] Path entry: without it every
// reinstall re-appends the app directory and Environment\Path truncates.
function NeedsAddPath(Param: string): Boolean;
var
  OrigPath: string;
begin
  if not RegQueryStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', OrigPath) then
  begin
    Result := True;
    exit;
  end;
  Result := Pos(';' + Uppercase(Param) + ';', ';' + Uppercase(OrigPath) + ';') = 0;
end;

// Surgical removal of our own entry at uninstall. Never done with
// uninsdeletevalue on the [Registry] entry: that flag deletes the whole
// Path value, taking every other program's entry with it.
procedure RemoveFromPath(Param: string);
var
  OrigPath: string;
  Position: Integer;
begin
  if not RegQueryStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', OrigPath) then
    exit;
  Position := Pos(';' + Uppercase(Param) + ';', ';' + Uppercase(OrigPath) + ';');
  if Position = 0 then
    exit;
  if Position = 1 then
    Delete(OrigPath, 1, Length(Param) + 1)
  else
    Delete(OrigPath, Position - 1, Length(Param) + 1);
  RegWriteExpandStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', OrigPath);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
    RemoveFromPath(ExpandConstant('{app}'));
end;
